baseurl = "https://favole.nicolaiarocci.com"
title = "Favole di Esopo Frigio"
languageCode = "it-IT"
theme = "casper"

copyright = "è un progetto di <a href=\"https://nicolaiarocci.com/\">Nicola Iarocci</a> &copy; 2017"
googleAnalytics = "UA-19006041-8"
description = "Le Favole di Esopo Frigio"

[params]
description = "Nuova edizione illustrata, e ridotta a più colta lezione, con aggiunta di molte altre Favole di varj accreditati Scrittori. In Venezia appresso Francesco Andreola, MDCCCVIII."
author = "Esopo Frigio"
logo = "images/esopo.png"
shareenabled = false

[[menu.main]]
name = "Home"
url = "/"
weight = 11

[[menu.main]]
name = "About"
url = "/about"
weight = 10

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
