baseurl = "http://favole.nicolaiarocci.com/"
title = "Favole di Esopo Frigio"
languageCode = "it-IT"
theme = "hemingway2"

copyright = "Favole di Esopo è un progetto di <a href=\"https://nicolaiarocci.com/\">Nicola Iarocci</a> &copy; 2017"
googleAnalytics = "UA-19006041-8"
description = "Le Favole di Esopo Frigio"
keywords = ["favole", "esopo"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[[params.social]]
url = "https://twitter.com/favolediesopo"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.facebook.com/favolediesopo/"
fa_icon = "fa-facebook"


[[params.social]]
url = "https://github.com/nicolaiarocci/favole"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.social]]
url = "https://github.com/nicolaiarocci/favole/blob/master/README.md"
fa_icon = "fa-info"
