baseurl = "http://favole.nicolaiarocci.com/"
title = "Favole di Esopo Frigio"
languageCode = "it-IT"
theme = "hemingway2"

copyright = "Favole di Esopo è un progetto di <a href=\"https://nicolaiarocci.com/\">Nicola Iarocci</a> &copy; 2017"
googleAnalytics = ""
description = "Le Favole di Esopo Frigio"
keywords = ["favole", "esopo"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[[params.social]]
url = "https://github.com/nicolaiarocci/esopo"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/nicolaiarocci"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
