baseurl = "http://favole.nicolaiarocci.com/"
title = "Favole di Esopo Frigio"
languageCode = "it-IT"
theme = "hemingway2"

copyright = "&copy; <a href=\"https://nicolaiarocci.com/\">Nicola Iarocci</a> 2017"
googleAnalytics = ""
description = "descrizione"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/nicolaiarocci"
fa_icon = "fa-github"

#[[params.social]]
#url = "https://gitlab.com/beli3ver"
#fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/nicolaiarocci"
fa_icon = "fa-twitter"

#[[params.social]]
#url = "https://telegram.me/beli3ver"
#fa_icon = "fa-telegram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
